apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: testcrds.stable.example.com
spec:
  group: stable.example.com
  names:
    kind: Testcrd
    listKind: TestcrdList
    plural: testcrds
    singular: testcrds
  scope: Cluster
  subresources:
    status: {}
  versions:
    - name: v1
      served: true
      storage: true