---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 'my-alameda.influxdb.pvc'
  namespace: "my-alameda"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: '10Gi'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 'my-alameda.grafana.pvc'
  namespace: "my-alameda"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi