---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alameda-datahub
  namespace: "my-alameda"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alameda-operator
  namespace: "my-alameda"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alameda-evictioner
  namespace: "my-alameda"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admission-controller
  namespace: "my-alameda"
