---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: alameda-datahub
  name: alameda-datahub
  namespace: "my-alameda"
spec:
  ports:
  - name: grpc
    port: 50050
  selector:
    app: alameda-datahub
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: admission-controller-tls
  labels:
    app: admission-controller
  name: admission-controller
  namespace: "my-alameda"
spec:
  ports:
  - port: 443
    targetPort: 8000
  selector:
    app: admission-controller
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: alameda-datahub-tls
  labels:
    app: alameda-influxdb
  name: alameda-influxdb
  namespace: "my-alameda"
spec:
  ports:
  - port: 8086
    targetPort: 8086
  selector:
    app: alameda-influxdb
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: alameda-grafana
  name: alameda-grafana
  namespace: "my-alameda"
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: alameda-grafana